export let GET_SUBJECT_LIST = "GET_SUBJECT_LIST";
export let GET_USER_LIST = "GET_USER_LIST";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const REQUEST_ERROR="REQUEST_ERROR";
export const REQUEST_START="REQUEST_START";
export const REQUEST_SUCCESS="REQUEST_SUCCESS";
